### ISSUE TITLE
ADC Arduino 

### ISSUE THREAD

**Issue by R41zan** [bverc/retropie-status-overlay#32] opened 2022-10-11 19:55 UTC
Trying to get my arduino board that deals with button input to read voltage on it's analogue pin.

Arduino Script:
![image](https://user-images.githubusercontent.com/39834067/195182887-3b9730a0-a497-436f-8c8c-93bd7fd26aa0.png)

Python Script: (file name: m32u4.py)
![image](https://user-images.githubusercontent.com/39834067/195185718-d254ba0a-f46f-4608-9eb7-fb5dd6db5119.png)

Config.ini file:
![image](https://user-images.githubusercontent.com/39834067/195185926-d47a0579-c06e-40ff-aa4d-653da53601c2.png)

Overlay.log Output: 
![image](https://user-images.githubusercontent.com/39834067/195186077-5916b11d-4efd-4a1e-8f63-786a79db4155.png)

is there anything else I have to update? im not getting the overlay to display anything, not even the rest of the items (bluetooth, wifi, sound)

Thanks

**Comment by R41zan** [comment] 2022-10-11 19:57
As soon as I put the battery option in config.ini to "False" and restart the service it starts to output this on the overlay.log:
![image](https://user-images.githubusercontent.com/39834067/195186535-c7899d26-8d80-4ddd-88b7-8987bfac186e.png)

And the overlay starts to work again

**Comment by R41zan** [comment] 2022-10-11 20:04
Modified python script to call the read function to be able to test output:
![image](https://user-images.githubusercontent.com/39834067/195187689-09b814ea-fc2b-4555-a107-597ea4470bb9.png)

The output: 
![image](https://user-images.githubusercontent.com/39834067/195187745-1842d566-742f-4a49-99ff-dedbdc28fa5d.png)

**Comment by bverc** [comment] 2022-10-12 00:14
Away from my computer, but I think I've spotted the issue. Using `if __name__ == "__main__"` means that code will not run when run as a module (as the script tries to do) but will work correctly when run directly.

Remove that line and unindent all below by one tab.

**Comment by bverc** [comment] 2022-10-12 00:20
Also. Stop the service then run the overlay.py manually. You should get an error output from python.

**Comment by bverc** [comment] 2022-10-12 01:22
Oh also, in your config file, replace `Multiplier` with `ADCGain`. Looks like that is a bug in the install script but example config file is correct.

**Comment by R41zan** [comment] 2022-10-12 05:55
Updated config.ini:
![image](https://user-images.githubusercontent.com/39834067/195261190-592799cf-9fc6-4627-934b-43cdefd00035.png)

Output: 
![image](https://user-images.githubusercontent.com/39834067/195261417-20f36087-4a90-4b1a-81ae-802bb47b69ec.png)

**Comment by bverc** [comment] 2022-10-12 06:30
Damn another bug in the install script. Can you please change `Type` to `ADCType` in your config file?

**Comment by R41zan** [comment] 2022-10-12 17:41
Output after updating ADCType: 
![image](https://user-images.githubusercontent.com/39834067/195411661-02ca9979-364b-46ab-b63e-bfe2321a3fd2.png)

**Comment by R41zan** [comment] 2022-10-12 17:56
> Damn another bug in the install script. Can you please change `Type` to `ADCType` in your config file?

It seems like it's now trying to get the state of the battery but i'm not sure i can get that from the arduino as the only thing i can read is the voltage

**Comment by R41zan** [comment] 2022-10-12 17:59
Never mind, the config.ini file was missing `# ADC Channel for ADCs which have multiple channels
ADCChannel = 0`

**Comment by R41zan** [comment] 2022-10-12 18:00
Got it to not faill completely and the led on the arduino is showing activity but i'm getting this error:
![image](https://user-images.githubusercontent.com/39834067/195415084-74343a3b-e8bf-418f-bba2-cb6c4dc962e4.png)

**Comment by R41zan** [comment] 2022-10-12 18:01
And the battery icon is still not showing on the display although now it shows the other 3 itens on the screen

**Comment by R41zan** [comment] 2022-10-12 18:22
So Amixer error is unrelated at this point. 

What could be causing the overlay to not display the battery icon even after getting the data? Data format? Because at this point it should be getting a value to the script from the function read()

**Comment by bverc** [comment] 2022-10-12 18:26
Great. Getting closer.

Looks like amixer cannot find your audio device. Can you try running `amixer` in the command prompt and dumping the results here?

Also try `amixer -c 1` and `amixer -c 2`

In the mean time. I suggest setting Audio to false while we try to get battery working.

**Comment by bverc** [comment] 2022-10-12 18:28
I think the program is just getting stuck once it gets to audio. Disabling that should make the others work.

`python3 overlay.py` should be putting out data every few seconds when working correctly.

**Comment by R41zan** [comment] 2022-10-12 18:31
Put a print on the python script to see what data if being returned by the read() function

![image](https://user-images.githubusercontent.com/39834067/195420625-d184c5a4-aca5-4b78-8b59-823356b5b3e3.png)

**Comment by R41zan** [comment] 2022-10-12 18:32
Audio is set to false and no longer gives a error
Still no battery icon or info

![image](https://user-images.githubusercontent.com/39834067/195420847-b08204b3-4d98-4735-acbb-360706ad19c0.png)

doesn't seem to go from 1 line of display info

**Comment by R41zan** [comment] 2022-10-12 18:32
Am i sending data too fast repeatedly?

**Comment by R41zan** [comment] 2022-10-12 18:34
to be clear the bluetooth and wifi icon still work fine

**Comment by bverc** [comment] 2022-10-12 18:40
When you say bluetooth and wifi work fine, do they change if you move out of range for example, or just the same as when they first load.

There are a few more errors in your config file which may be causing it to get stuck, I'm not sure.

Try `VMaxCharging = 4.7` since you are returning higher vslues than I would expect.
Also `ADCShutdown = False` not `N`

**Comment by R41zan** [comment] 2022-10-12 18:42
I've updated my config.ini to the config.ini.example and re-did it so it should be fine now. 

Bluetooth changes state when i connect somethig and wifi changes signal strengh

ill try with higher VmaxCharging

**Comment by bverc** [comment] 2022-10-12 18:47
Please also share your m32u4.py

**Comment by R41zan** [comment] 2022-10-12 18:47
No changes. It doesn't change icon behavior

also updated config.ini:
![image](https://user-images.githubusercontent.com/39834067/195423625-40e55c14-1afd-4fe8-8771-0025c68d8131.png)

**Comment by R41zan** [comment] 2022-10-12 18:48
File m32u4.py
`
#!/usr/bin/env python3

#Import necessary library
import serial
import time

def read(channel):
    ser = serial.Serial('/dev/ttyACM0', 9600, timeout=1)
    ser.reset_input_buffer()
    while True:
          value_v = ser.readline().decode('utf-8').rstrip()
    return value_v
`

**Comment by R41zan** [comment] 2022-10-12 18:48
![image](https://user-images.githubusercontent.com/39834067/195423868-f37b9ca5-5c06-4050-bcfe-0892aa14062f.png)

**Comment by bverc** [comment] 2022-10-12 18:51
Aha! Ok it's getting stuck in your while loop.

Remove `while True:` and pull in the next line.

`while True` will never exit.

**Comment by R41zan** [comment] 2022-10-12 18:56
Alright, something different:

![image](https://user-images.githubusercontent.com/39834067/195425279-86107098-39e6-4a7b-b286-12efb3242ef9.png)

**Comment by R41zan** [comment] 2022-10-12 18:57
i probably shouldn't be opening a serial connection everytime the function is called, right?
move the serial out and only have the buffer reset and value_v in the read()?

**Comment by R41zan** [comment] 2022-10-12 19:01
its getting a string from the read() instead of float or int

**Comment by R41zan** [comment] 2022-10-12 19:04
I have battery info!!!!

**Comment by R41zan** [comment] 2022-10-12 19:05
that was the issue. 
Fixed it by changing 
`return value_v` to `return float(value_v)`

**Comment by bverc** [comment] 2022-10-12 19:06
Glad to hear.

Yes I would move first two lines out of the read function and put in a `try` so it will fail elegantly if it cannot communicate with your ADC.

Can you post your final code?

**Comment by R41zan** [comment] 2022-10-12 19:07
Sure can! Thank you so much for your help! 

I'm just going to add that 

What exception would you recomend on the `try`?

**Comment by bverc** [comment] 2022-10-12 19:09
RuntimeError will be fine. Just copy the other module.

**Comment by R41zan** [comment] 2022-10-12 19:18
Will do that 
BTW should i completely remove the serial dealy and just let it send as much data as possible to get better avg and thus better (more accurate?) voltages or go the opposite route and increase delay to send less data?

**Comment by bverc** [comment] 2022-10-12 19:25
Which delay are you referring? Let the main script determine the polling frequently not your module.

**Comment by R41zan** [comment] 2022-10-12 19:30
On the arduino side i have a 500 delay

**Comment by bverc** [comment] 2022-10-12 19:41
Actually that is a good point. Overlay will pull data from the buffer slower than the arduino puts it on. Which means without clearing the buffer before a read it could be pulling old data.

I suggest reducing delay so something like 100, but then clearing the buffer before doing a read to request the latest value. 100ms means it won't need to wait too long.

To test, put your battery on and off charging and check you get immediate response in the overlay log voltage reading (not the icon as this uses a rolling average)

Hope that makes sense.

**Comment by R41zan** [comment] 2022-10-12 19:45
![image](https://user-images.githubusercontent.com/39834067/195433647-d219a689-c5f9-4fe8-92e7-6c270734d42a.png)

Tested no delay on serial send from the arduino. 
The quantity of info sent must overflow/"mix" with the quantity in the buffer and eventually it craps itself. Also note that theres a couple of voltages that are anormal - 18 and 3 in this case

**Comment by R41zan** [comment] 2022-10-12 19:47
def read(channel):
    ser.reset_input_buffer()
    value_v_string = ser.readline().decode('utf-8').rstrip()
    value_v = float(value_v_string)
    return value_v

my read() is currently like this so when it's called it should clear the buffer and read a new line sent by the arduino
at some point this must cut in the middle of some bytes being sent by the arduino and convert the bytes to utf-8 in a way that creates abnormal numbers (?)

**Comment by R41zan** [comment] 2022-10-12 19:50
Arduino side: 
![image](https://user-images.githubusercontent.com/39834067/195434646-c561fd3b-5a4b-4228-99ca-3e25b73461d3.png)

Will change serial print to write to send bytes instead of readeable data to see if it helps with consistency

**Comment by R41zan** [comment] 2022-10-12 19:53
nvm that would complicate things quite alot

**Comment by bverc** [comment] 2022-10-16 10:16
Added a modified version of the python module to the branch `serial-test`. Can you please test it works on your setup?

In the config.ini, set `ADCType = SER`

Not sure what to name the module, as it cannot be "serial" due to conflict with the library module name.

**Comment by scavenrage** [comment] 2024-03-19 21:53
Hi, can you please post the final m32u4.py? I'm trying to follow your comment to have the final version but I'm still not getting the battery icon... 
Thanks

**Comment by scavenrage** [comment] 2024-03-19 22:07
Oh nevermind, I've just succeed to have the battery info! 
I've used the GPIO serial port with an Attiny85 that reads the voltage with the analog input.

the final version of the file is


#!/usr/bin/env python3

#Import necessary library
import serial
import time
ser = serial.Serial('/dev/ttyS0', 9600, timeout=1)
ser.reset_input_buffer()
def read(channel):
    value_v = ser.readline().decode('utf-8').rstrip()
    return float(value_v)

![ardu py](https://github.com/bverc/retropie-status-overlay/assets/22749827/316f62a4-94f0-45fd-8c08-ac1f51444390)

**Comment by bverc** [comment] 2024-03-19 23:29
Hi @scavenrage 
Did you test the `ser` module on the `serial-test` branch?

You code looks very close to what we arrived at in `ser.py`, except you are using `/dev/ttyS0` instead of `/dev/ttyACM0` (assume because you are not connected via USB. I assume this would therefore need to be customizable?

Can you please check the ser module suits your needs? If so, I can modify to make the port SERIAL_DEVICE configurable.

**Comment by scavenrage** [comment] 2024-03-20 00:44
Hi,
I used ttyS0 because I'm not using USB but I'm connected directly with the gpio15 that is the rxd of the pi (in this case it's a CM4 but it's the same).

I'm sorry but I didn't test the ser module, only because I didn't know how to do that! I just found out now how a branch works. Tomorrow (here it's 2am) I will come back with the result

**Comment by bverc** [comment] 2024-03-20 07:27
Makes sense.
Yea give it a go, and if you are happy it works, I can merge it in. It was never confirmed as working previously, and I was unable to test.

As the module can't read from config file, the SERIAL_DEVICE can't be set outside the module. Open to ideas how to do this. Can add some comments in the module to offer examples.

**Comment by scavenrage** [comment] 2024-03-20 16:51
Hi bverc,

just finished now testing the ser module, works like a charm!  I 've just had to do a correction, because without that it does not work.
the correction is (as saw in the discussion before) to change return value_v to return float(value_v).
And of course I've changed the serial port because i used the ttyS0 (it works also putting "serial0" instead of ttyS0).

Sadly I don't have any good idea to set the serial device other than just writing it in the module after searching for the serial ports available with the command "dmesg | grep tty"
![IMG_20240320_173700](https://github.com/bverc/retropie-status-overlay/assets/22749827/dd3aa544-1811-430f-94de-55c8c490fb76)

**Comment by bverc** [comment] 2024-03-21 08:31
Great, glad it is working for you. I'll get that line tidied up and merged in. Cheers for testing it out.

**Closed as completed** 2024-04-09 09:55 UTC
